export const MODULE_SHELLS = Object.freeze({
  math: {
    title: "Math Mountain",
    routeKey: "math",
    desktopSrc: "/assets/landing/math/math_non-mobile_background.png",
    mobileSrc: "/assets/landing/math/math_mobile_background.png",
    desktopWidth: 1536,
    desktopHeight: 1024,
    mobileWidth: 887,
    mobileHeight: 1774,
    desktopSizes: "(max-width: 1536px) 100vw, 1536px",
    mobileSizes: "(max-width: 768px) 100vw, 887px",
    summary: "Math Mountain will include grade-based math adventures, puzzles, drills, and learning challenges.",
  },
  skills: {
    title: "Skills Sea",
    routeKey: "skills",
    desktopSrc: "/assets/landing/skills/skills_non-mobile_background.png",
    mobileSrc: "/assets/landing/skills/skills_mobile_background.png",
    desktopWidth: 1672,
    desktopHeight: 941,
    mobileWidth: 887,
    mobileHeight: 1774,
    desktopSizes: "(max-width: 1672px) 100vw, 1672px",
    mobileSizes: "(max-width: 768px) 100vw, 887px",
    summary: "Skills Sea will include keyboard, mouse, focus, and dexterity games for young learners.",
  },
  coding: {
    title: "Code Cavern",
    routeKey: "coding",
    desktopSrc: "/assets/landing/coding/coding_non-mobile_background.png",
    mobileSrc: "/assets/landing/coding/coding_mobile_background.png",
    desktopWidth: 1672,
    desktopHeight: 941,
    mobileWidth: 887,
    mobileHeight: 1774,
    desktopSizes: "(max-width: 1672px) 100vw, 1672px",
    mobileSizes: "(max-width: 768px) 100vw, 887px",
    summary: "Code Cavern will introduce sequencing, logic, loops, and problem-solving activities.",
  },
  readingReference: {
    title: "Reading Rainforest Reference",
    routeKey: "readingReference",
    desktopSrc: "/assets/landing/reading/reading_non-mobile_background.png",
    mobileSrc: "/assets/landing/reading/reading_mobile_background.png",
    desktopWidth: 1536,
    desktopHeight: 1024,
    mobileWidth: 887,
    mobileHeight: 1774,
    desktopSizes: "(max-width: 1536px) 100vw, 1536px",
    mobileSizes: "(max-width: 768px) 100vw, 887px",
    summary: "Prototype-only visual reference for Reading Rainforest controls.",
  },
  reading: {
    title: "Reading Rainforest",
    routeKey: "reading",
    desktopSrc: "/assets/landing/reading/reading_non-mobile_background.png",
    mobileSrc: "/assets/landing/reading/reading_mobile_background.png",
    desktopWidth: 1536,
    desktopHeight: 1024,
    mobileWidth: 887,
    mobileHeight: 1774,
    desktopSizes: "(max-width: 1536px) 100vw, 1536px",
    mobileSizes: "(max-width: 768px) 100vw, 887px",
    summary: "Reading Rainforest will introduce advanced reading, comprehension and WPM controls.",
  },
});
